export const accommodationTypes = [
    'Hotel',
    'Holiday home',
    'Villa',
    'Tiny house',
    'Holiday apartment',
    'Chalet',
    'Bungalow',
    'Houseboat',
    'Guesthouse',
    'Yurt',
    'Log cabin',
    'Campervan',
    'Farmhouse',
    'Tent',
    'Treehouse'
  ];
  
  export const mainFilters = [
    'Fenced garden',
    'Dog allowed in the restaurant',
    'Parking at the accommodation',
    'Free cancellation',
    'Private pool',
    'Kids friendly'
  ];
  
  export const dogFilters = [
    'Dog stays free of charge',
    'Private garden',
    'Leash required',
    'No leash required',
    'Off-leash meadow',
    'Fenced garden up to 1m',
    'Fenced garden up to 1.20m',
    'Fenced garden up to 1.50m',
    'Fenced garden up to 2m',
    'Fenced terrace',
    'Allowed at the pool area',
    'Allowed in the restaurant',
    'Firework-free zone',
    'Dog-friendly beach nearby',
    'Food bowl',
    'Water bowl',
    'Dog bed',
    'Dog blanket',
    'Dog mat',
    'Dog shower',
    'Dog-friendly restaurants nearby',
    'Dog treats',
    'Dog pool',
    'Agility area',
    'Mantrailing',
    'BARF menus available',
    'Fenced dog park',
    'Dog forest nearby',
    'Dog park (not fenced)',
    'Poop bags for free',
    'Allowed on the bed',
    'Allowed on the sofa',
    'Dog menu',
    'Dog trailer (bicycle)',
    'Dog crate',
    'Dog house',
    'Dog room service',
    'Dog physiotherapy',
    'Dog sitter',
    'Dog school',
    'Dog shop',
    'Dog trainer',
    'Dog towels',
    'Cage',
    'Organized hiking tours with dogs',
    'Sign for "Dog is a guest here"',
    'Wellness for dogs',
    'Service dog for free'
  ];